FROM node:lts

WORKDIR /app

COPY . .

ARG PORT=8090
ARG APOLLO_ENGINE_API_KEY="YOUR_API_KEY"
ARG SCHEMATA_TO_GRAPHQL="auth,auth_fn,org,org_fn,app,prj"
ARG POSTGRES_CONNECTION="postgres://postgres:1234@0.0.0.0/pg_phile_starter"
ARG DEFAULT_ROLE="app_anonymous"
ARG JWT_SECRET="SUPERSECRET-SUPERSECRET-SUPERSECRET"
ARG JWT_PG_TYPE_IDENTIFIER="auth.jwt_token"
ARG EXTENDED_ERRORS="hint, detail, errcode"
ARG DISABLE_DEFAULT_MUTATIONS="false"
ARG DYNAMIC_JSON="true"
ARG ENABLE_APOLLO_ENGINE="false"
ARG WATCH_PG="true"
ARG GRAPHIQL="true"
ARG ENABLE_CORS="true"

ENV PORT=$PORT
ENV APOLLO_ENGINE_API_KEY=$BLAH
ENV SCHEMATA_TO_GRAPHQL=$BLAH
ENV POSTGRES_CONNECTION=$BLAH
ENV DEFAULT_ROLE=$DEFAULT_ROLE
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_PG_TYPE_IDENTIFIER=$JWT_PG_TYPE_IDENTIFIER
ENV EXTENDED_ERRORS=$EXTENDED_ERRORS
ENV DISABLE_DEFAULT_MUTATIONS=$DISABLE_DEFAULT_MUTATIONS
ENV DYNAMIC_JSON=$DYNAMIC_JSON
ENV ENABLE_APOLLO_ENGINE=$ENABLE_APOLLO_ENGINE
ENV WATCH_PG=$WATCH_PG
ENV GRAPHIQL=$GRAPHIQL
ENV ENABLE_CORS=$ENABLE_CORS

RUN yarn install

EXPOSE $PORT

ENTRYPOINT ["node", "dist/server.js"]
